### ISSUE TITLE
Used 5V adapter instead 3,3V. Do you know if only the ESP is destroyed?

### ISSUE THREAD

**Issue by jonalbr** [HomeKidd/ESP8266-HomeKit-Air-Quality-Sensor-Elgato-Eve-Room#13]
Hi,

EDIT:

I just found a datasheet for the adapter I used and it provides 5V instead of 3,3V. 

So I guess I fried something. Do you know if I only need to change the ESP or could this affect more?

ORIGINAL:

I Assembled￼ the PCB ￼as you described it. I tried to flash it, however it just starts to "sync" and nothing else happens. Should this take seconds or several minutes?

![image](https://user-images.githubusercontent.com/68380809/114434444-4dbb9880-9bc3-11eb-8a58-52e6e13ecc43.jpeg)￼
![image](https://user-images.githubusercontent.com/68380809/114434465-544a1000-9bc3-11eb-91df-61e1c67c72df.jpeg)
![image](https://user-images.githubusercontent.com/68380809/114434472-56ac6a00-9bc3-11eb-9988-6cfac879ec3f.jpeg)

Or is something wrong configured? I thought I matched your specs. 

How I set the ESP into boot loader mode: 1. connect the micro usb for power 2. Press and hold button 3. Connect usb of the adapter 4. Release button 5. Press "start" of the download tool

Thank you so much for your help!
Jonas

**Comment by HomeKidd** [comment]
Hi!

Some adapters have a jumper on the PCB for selecting 5V/3.3V. Also some FTDI adapters have inverse TX/RX pins. Did you tried to flash it by changing the TX/RX pins? In normal situation for flashing you need to connect the adapters RX to the ESP's TX and vica versa RX to TX. My adapters are already inverse so i always connect TX-TX and RX-RX.

Its possible that the ESP is dead due to the 5V beacuse the TX/RX pins are only 3.3V tolerant on all ESP boards. You can try to power it via USB, the built-in blue LED on the ESP should flash once when you plug it into power, that way you can check is it fried or not. Changing the ESP on the PCB also could help if its fried.

**Comment by jonalbr** [comment]
The LEDs flash but The ESP Flash tool dosen't recognise the ESP anymore. I'll just start over :) some more practice in soldering is probebly useful for me.

**Comment by jonalbr** [comment]
I could flash a second ESP on a differned PCB! (Do I have to keep the button pressed during the whole flash or just during the "connecting to PC" part for a couple of seconds?)

Somehowe I've got a new question now: What does the two pin openings do? Am I supposed to connect something to them? I marked them red in the picture. I connected the USB to the area I marked green. However I just discovered this method does not power my ESP well. The blue led just flicked a bit when I moved the USB Cable/port a little bit around (like a loose contact). Otherwise it just stays dark. Can you maybe post a close up picture how you soldered the micro USB port? That would hopfully help a lot. I attatched my try below :)
![108688601-65966a80-74f8-11eb-8572-25ae127a52ff](https://user-images.githubusercontent.com/68380809/114772608-4be20880-9d6e-11eb-99a4-906d32f50f72.jpeg)

A picture of how I thought the USB port is soldered:
![image](https://user-images.githubusercontent.com/68380809/114781174-a1bbae00-9d78-11eb-85dd-9e66656a94f0.jpeg)
@HomeKidd

**Comment by HomeKidd** [comment]
> I could flash a second ESP on a differned PCB! (Do I have to keep the button pressed during the whole flash or just during the "connecting to PC" part for a couple of seconds?)

You need to press the button and pressing it while powering up the USB adapter, after that you can release it. The button need to be held low ( aka pushed) when the ESP powers up ( aka you plug in the adapter to PC) because it can only enter **boot mode** in that way.

> What does the two pin openings do? 

Those are external power supply pins, the rectangle one should be +5V, the round is GND. I've added it for safety 😄 I dont have any photos of the PCB because I'm using these two pins to power it up, also on my newer/other designs i've started using USB Type-C 😄

**Comment by jonalbr** [comment]
Thanks for that! Do you know if it's a problem if not only the far left and far right pin of the micro USB port is soldered? Like when due to my limited skills for example the VCC and D- pin are shorted?

**Comment by HomeKidd** [comment]
> VCC and D- pin are shorted?

Solder bridge between these pins can be a problem from the USB cable / wall adapter part, but on the PCB only 5V and GND are connected from the USB because of this 🤓

**Comment by jonalbr** [comment]
Thanks for the quick reply. I'll try my best to fix that than :)
