### ISSUE TITLE
VOC density as value?

### ISSUE THREAD

**Issue by jonalbr** [HomeKidd/ESP8266-HomeKit-Air-Quality-Sensor-Elgato-Eve-Room#15]
Hi, is it possible to see the VOC density as a value like ppb in the eve or home app? Additionally to the five stars as indicators for Air Quality.
Great work!

Best regards
Jonas

**Comment by HomeKidd** [comment]
You can see it in the Home app when you open the accessory’s setting page:

![11E401E8-DE4B-4E3E-9710-7CB84C172BF4](https://user-images.githubusercontent.com/53994826/116284660-9c555f00-a78d-11eb-9cf9-1a8086fa0f03.png)

**Comment by jonalbr** [comment]
Hi @HomeKidd 
This is somehow not available for me. 

![image](https://user-images.githubusercontent.com/68380809/116286007-0cb0b000-a78f-11eb-8e0f-8481922d7efa.png)
![image](https://user-images.githubusercontent.com/68380809/116286146-2baf4200-a78f-11eb-9e41-083b2d9832e7.png)

**Comment by HomeKidd** [comment]
The Eve app doesnt show the VOC because it should be part of the Eve history which is dont have (yet)😁
The Home app has it but german translation (like my Hungarian one😅) spells all the words of VOC, not like the english translation 😬 its the Home app’s / translation’s mistake 😬
If you set the language to US on the phone i’m 100% sure you’ll see the text and the values too 🤓
Sadly you cant do anything with that, its an Apple/Home app related problem 🤷🏻‍♂️😩
